image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.10.1

stages:
  - build
  - release

build-branches:
  stage: build
  script:
    - mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true -U
  only:
    - branches
  except:
    - master
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/

build:
  stage: build
  script:
    - mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent  test -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true -U
  only:
    refs:
      - master
      - tags
      - /^release-.*$/
      - /^hotfix-.*$/

release:
  stage: release
  script:
    - mvn package deploy -Dmaven.test.skip=true
  only:
    - master
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/
    
.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
  - *auto_devops