image: registry.cn-hangzhou.aliyuncs.com/macula-cloud/ci-base:0.9.1

stages:
  - mvn-package
  - maven-deploy

maven-test-branches:
  stage: mvn-package
  script:
    - mvn package -DskipTests=true
  only:
    - branches
  except:
    - master
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/

maven-test-build:
  stage: mvn-package
  script:
    - mvn clean package -U
  only:
    - master
    - /^release-.*$/
    - /^hotfix-.*$/

maven-deploy-snapshot:
  stage: maven-deploy
  script:
    - mvn clean install -DskipTests=true deploy
  only:
    - master

maven-deploy-release:
  stage: maven-deploy
  script:
    - mvn clean install -DskipTests=true deploy
  only:
    - tags
    - /^release-.*$/
