image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.10.1

variables:
  MAVEN_OPTS: -s .m2/settings.xml --batch-mode -Dmaven.repo.local=.m2/repository

stages:
- build
- release

build-branches:
  stage: build
  script:
  - mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true -U $MAVEN_OPTS
  only:
  - branches
  except:
  - master
  - tags
  - /^release-.*$/
  - /^hotfix-.*$/

build-main:
  stage: build
  script:
  - mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent  test -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true -U $MAVEN_OPTS
  only:
    refs:
    - master
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/

release-main:
  stage: release
  script:
  - mvn package deploy -Dmaven.test.skip=true $MAVEN_OPTS
  only:
  - master
  - tags
  - /^release-.*$/
  - /^hotfix-.*$/