image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.10.1

stages:
  - build
  - release

build-branches:
  stage: build
  script:
    - mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true -U
  only:
    - branches
  except:
    - master
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/

build:
  stage: build
  script:
    - mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent  test -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true -U
  only:
    refs:
      - master
      - tags
      - /^release-.*$/
      - /^hotfix-.*$/

release:
  stage: release
  script:
    - mvn package deploy -Dmaven.test.skip=true
  only:
    - master
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/